In [2]:
import pandas as pd
data = pd.read_csv('Student.csv')
print(data)

   result
0    Pass
1    Fail
2    Pass
3    Pass
4  Absent
5    Fail
6    Fail
7    Pass
8    Pass
9  Absent


In [3]:
result_category=data['result']


In [4]:
from sklearn.preprocessing import LabelEncoder
object=LabelEncoder()
result=object.fit_transform(result_category)
print(result)


[2 1 2 2 0 1 1 2 2 0]


In [7]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
result1=ohe.fit_transform(result_category.values.reshape(-1,1))
result1.toarray()

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [8]:
from sklearn.preprocessing import LabelBinarizer
lb=LabelBinarizer()
result2=lb.fit_transform(result_category)
print(result2)


[[0 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]]


In [11]:
object.classes_


array(['Absent', 'Fail', 'Pass'], dtype=object)

In [12]:
lb.classes_


array(['Absent', 'Fail', 'Pass'], dtype='<U6')

In [13]:
ohe.categories_


[array(['Absent', 'Fail', 'Pass'], dtype=object)]